# Generated by Django 3.2.8 on 2022-06-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLShorten',
            fields=[
                ('short', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('url', models.URLField()),
            ],
        ),
    ]
