# Generated by Django 3.2.8 on 2022-06-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshorten',
            name='url',
            field=models.URLField(db_index=True),
        ),
    ]
